### ISSUE TITLE
Connecting to Events (KeyPressEvent, WheelEvent, Move, Resize etc)

### ISSUE THREAD

**Issue by ilius** [mappu/miqt#69] opened 2024-11-10 12:52 UTC
Hi

I'm using `qt6` package.

There are several widget signals I could not figure out how to connect to (register a func to run)

- [keyPressEvent](https://doc.qt.io/qt-6/qwidget.html#keyPressEvent)
- [moveEvent](https://doc.qt.io/qt-6/qwidget.html#moveEvent)
- [resizeEvent](https://doc.qt.io/qt-6/qwidget.html#resizeEvent)
- [mouseReleaseEvent](https://doc.qt.io/qt-6/qwidget.html#mouseReleaseEvent)
- [wheelEvent](https://doc.qt.io/qt-6/qwidget.html#wheelEvent)
- [contextMenuEvent](https://doc.qt.io/qt-6/qwidget.html#contextMenuEvent)

I also could not figure out how to use `QObject.Connect2` manually for these.

**Comment by mappu** [comment] 2024-11-11 05:23
MIQT supports Qt signals well, but in C++ those examples are not signals, but rather virtual override class methods. Qt uses this technique for methods that might be called with a high frequency. 

Duplicate of #42 . Work is in progress to support this very soon.

**Closed** 2024-11-19 08:50 UTC
Labels: duplicate
