### ISSUE TITLE
How goroutine works when updating asynchronously

### ISSUE THREAD

**Issue by st0pli** [mappu/miqt#111] opened 2024-12-21 02:04 UTC
QObject: Cannot create children for a parent that is in a different thread.
(Parent is QHeaderView(0x600001dea2b0), parent's thread is QThread(0x6000011d8320), current thread is QThread(0x6000011d7590)
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread
QBasicTimer::start: QBasicTimer can only be used with threads started with QThread

**Comment by rcalixte** [comment] 2024-12-21 04:24
What version of the miqt Go module are you using? I believe this was fixed on 0.7.0 and later versions.

**Comment by mappu** [comment] 2024-12-29 02:33
Miqt affixes Go's main startup goroutine to a Qt thread. But if you use other goroutines, they would not be pinned to the same OS thread, and Qt complains about it.

Duplicate of #76

**Comment by mappu** [comment] 2024-12-30 04:20
Hi @st0pli , it should now be working in master.

1. Please update Miqt to the latest Git master version.
2. `import "github.com/mappu/miqt/qt6/mainthread"`
3. `mainthread.Wait(func() { /* do something */ })`

Please try it out, and let me know if you have any problems,

**Closed by mappu** 2024-12-30 04:20 UTC
Labels: duplicate, essential

**Comment by st0pli** [comment] 2025-01-09 11:49
> Hi @st0pli , it should now be working in master.
> 
> 1. Please update Miqt to the latest Git master version.
> 2. `import "github.com/mappu/miqt/qt6/mainthread"`
> 3. `mainthread.Wait(func() { /* do something */ })`
> 
> Please try it out, and let me know if you have any problems,

@mappu Does qt5 support it as well?

**Comment by mappu** [comment] 2025-01-11 04:11
@st0pli A new version for Qt5 is added in PR #130.
