### ISSUE TITLE
Migration from therecipe/qt to mappu/miqt

### ISSUE THREAD

**Issue by akiyosi** [mappu/miqt#94] opened 2024-11-23 14:48 UTC
I am considering moving from therecipe/qt to mappu/miqt.
First I want to migrate the following frameless window repository.
https://github.com/akiyosi/goqtframelesswindow

Does mappu/miqt have any methods to access native Windows events?

**Comment by mappu** [comment] 2024-11-23 21:23
Miqt doesn't have this yet (duplicate of #59). Currently, the bindings only include functions and typedefs that work on all platforms, but these functions have different typedefs on Windows vs Linux or other platforms.

It could be fixed in Miqt soon. Until then, since Miqt is a simple CGO binding, one possible workaround is to add a .cpp file to your Go package:

example.cpp

```cpp
#include "example.h"
#include <QWidget>

void native_operation(void* target_qwidget) {
    QWidget* w = static_cast<QWidget*>(target_qwidget);
#ifdef Q_OS_WIN
    HWND h = w->winId();
    // ... more code here
#else
    // other OS implementation...
#endif 
}
```

example.h

```c
#ifdef cplusplus
extern "C" {
#endif 

void native_operation(void* target_qwidget);

#ifdef cplusplus
}
#endif 
```

example.go

```golang
import (
    qt "github.com/mappu/miqt/qt6"
)

/*
#include "example.h"
*/
import "C"

func NativeOperation(w *qt.QWidget) {
    C.native_operation(w.UnsafePointer())
}
```

Not tested, but, this idea lets you do anything that is possible in Qt C++.

**Comment by akiyosi** [comment] 2024-11-24 04:09
@mappu 
Thanks for the quick reply.
I will follow up with #59 on the native events.

Let me confirm one more point.
In therecipe/qt, no explicit type conversion was required for those that are in an inheritance relationship on the Qt side.
On the other hand, mappu/miqt seems to require type conversion as follows. (please point out if I am wrong in my usage)

``` go
	w := qt.NewQWidget(nil)
	layout := qt.NewQVBoxLayout(w)

	// No need for type conversion like therecipe/qt
	w.SetLayout(layout)

	// Need type conversion
	w.SetLayout((*qt.QLayout)(unsafe.Pointer(layout)))

```

Is there any plan to make it possible to omit explicit type conversion in the future, similar to therecipe/qt?

**Comment by mappu** [comment] 2024-11-25 04:44
The type conversion is required, but your example is incorrect, it can be much simpler: `layout.QLayout` as per FAQ Q5.

When this binding started, I wanted to create everything from scratch, to have a clean MIT license and not be influenced by therecipe/qt 's LGPL code. But now that MIQT is starting to become more mature, it would be good to make small changes to simplify porting.

The technique therecipe/qt uses for type casting is an interface, which causes an increased pointer indirection, but that's probably not a problem.

**Closed** 2024-11-25 16:49 UTC
Labels: duplicate
